---
title: "cyano_16S_graph_alpha"
author: "Dylan Barth"
date: "2026-02-25"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(colorspace)
library(phyloseq)
library(ggh4x)
library(DBI)
library(picante)
library(vegan)
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = '~/WorkForaging/Academia/Nicole/deca/')
```


## Import data

First we import the subset of data that corresponds to only phylum `Cyanobacteriota`. Some samples were pruned out due to lacking any ASVs within this phylum, but 761 samples remain. 

```{r import}
ps <- readRDS("data/cyano/phyloseq.cyano.tree.rds")
meta <- data.frame(sample_data(ps)) %>% rename("Sample"="SampleID")
otu <- data.frame(otu_table(ps))

```




## Calculate alpha indices

Next we calculate each of the metrics we are interested in, these are Richness, Evenness, Shannon, Simpson and Faith alpha indices. 

```{r alphas}

rich <- vegan::specnumber(otu)
shan <- vegan::diversity(otu, index = 'shannon')
simp <- vegan::diversity(otu, index = 'simpson')
peven <- shan / log(rich)

faith <- pd(otu, phy_tree(ps), include.root = F)

```


```{r graph-alphas}
gdat <- left_join(meta,  data.frame(richness=rich, Sample=names(rich)), by='Sample')
gdat <- left_join(gdat,  data.frame(shannon=shan, Sample=names(shan)), by='Sample')
gdat <- left_join(gdat,  data.frame(simpson=simp, Sample=names(simp)), by='Sample')
gdat <- left_join(gdat,  data.frame(evenness=peven, Sample=names(peven)), by='Sample')
gdat <- left_join(gdat, data.frame(faith=faith$PD, Sample=rownames(faith)), by="Sample")

gdat <- gdat %>% group_by(Sample) %>% pivot_longer(cols = c(richness, shannon, simpson, evenness, faith), names_to = 'metric', values_to = 'Alpha')

treatcols <- c("#E5AE71","#71C4E5","#53DF7B","#C0E5A4","#BCE7D6","#DF53B7","#E7BCCC","#804DEF")
treatlevs <- c("Control","Water","N", "N+P","N+Water","P","P+Water","N+P+Water")
timelevs <- c("Nov_2022","Feb_2023", "Aug_2023","Nov_2023", "Feb_2024","Aug_2024")
mshapes <- c(17,16)

gdat <- gdat %>% filter(SampleDate!='Jul_2022', Microhabitat %in% c("SI","SG","SSI","SSG")) 
gdat <- gdat %>% mutate(SampleDate=factor(SampleDate, levels=timelevs), 
                        Treatment=factor(Treatment, levels=treatlevs), 
                        Microhabitat = factor(Microhabitat, levels= c("SI","SG","SSI","SSG")))
#gdat2 <- gdat %>% filter(Treatment=='Control') %>% group_by()

g1 <- ggplot(gdat)+
  #geom_jitter(aes(x=SampleDate, y=Alpha, color=Treatment, shape=Grass_Interspace), height=0, width=0.4)+
  geom_boxplot(aes(x=SampleDate, y=Alpha, fill=Treatment))+
  facet_grid2(Microhabitat~metric, scales='free', independent='all',switch = 'y')+
  scale_fill_manual(values = treatcols)+
  scale_shape_manual(values = mshapes)+
  theme_bw()+
  theme(text = element_text(size=15),
        axis.text.x = element_text(angle = 45, vjust=.9, hjust=.9))

ggsave('figs/cyano_alpha_boxplot.png', g1, width = 7000, height=4000 ,units='px')

g1

```
